name: Create PR

on:
  repository_dispatch:
    types: [payments-sync-ready]
permissions:
  contents: write

jobs:
  Create-PR:
    runs-on: ubuntu-latest
    env:
      PAT: ${{ secrets.PAT}}
      GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
      GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
      REPO_OWNER: ${{ secrets.REPO_OWNER }}
      REPO_NAME: ${{ secrets.REPO_NAME }}

    steps:
      - name: Checkout main repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name ${GIT_USERNAME}
          git config --global user.email ${GIT_EMAIL}

      - name: Set up Git credentials
        run: |
          git config --global credential.helper 'store'
          echo "https://x-access-token:${PAT}@github.com" > ~/.git-credentials

      - name: Remove all files except .git, .github, and .gitignore
        run: |
          find . -mindepth 1 -maxdepth 1 ! -name '.git' ! -name '.github' ! -name '.gitignore' -exec rm -rf {} +

      - name: Clone remote repository
        run: |
          git clone https://x-access-token:${{ secrets.PAT }}@github.com/johnathanbo/jb-cicd-playground.git

      - name: Copy changes from remote repository
        run: |
          cp -r jb-cicd-playground/payments/* .
          rm -rf jb-cicd-playground
          git checkout -b sergey-staging
          git add .
          git commit -m "[AUTOMATED] Sync payments folder from remote repo"

      - name: Push changes to new branch
        run: |
          git push https://x-access-token:${PAT}@github.com/johnathanbo/jb-cicd-playground.git sergey-staging

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.PAT }}
          commit-message: Syncing changes to main repo
          title: "[Automated] Sync changes from remote repo"
          body: This PR syncs changes from the remote repository to the main repository.
          reviewers: johnathanbo
          branch: sergey-staging
          base: main
